version: "3"
services:
    my-redis:
        image: redis:lastest
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports: 
            - 6379:6379
        networks: 
            - my-network
networks: 
    my-network: